### ISSUE TITLE
Recent PR Templates Install Not Working

### ISSUE THREAD

**Issue by StarlingLecter** [cschleiden/azure-devops-pr-templates#12] opened 2019-01-04 15:52 UTC
We recently assisted a developer at our company install PR Templates as an extension in TFS.

See article: https://marketplace.visualstudio.com/items?itemName=cschleiden.prtemplates#overview

He created and saved a PR template, but when he goes to apply it to the pull request (as demoed in the link I sent), nothing shows up. There is no result. 

He currently has build admin permissions in this collection. Am I missing something permission-wise?

Thank you,

Alex

**Comment by cschleiden** [comment] 2019-01-04 16:49
That is interesting.. I can repro on a TFS 2019 install. I don't have time to investigate right now, I'll try to get back to it next week, if no one beats me to it.

**Comment by nschonni** [comment] 2019-01-04 18:00
Think it's the same as this https://github.com/cschleiden/azure-devops-pr-templates/issues/10#issuecomment-444187450 that something changed after 1.0.0 broke

**Comment by cschleiden** [comment] 2019-01-04 18:06
Yes, it's the same. I have a fix, just need to publish an update.

**Comment by cschleiden** [comment] 2019-01-04 18:06
Duplicate of #10

**Closed by cschleiden** 2019-01-04 18:06 UTC
Labels: bug
